# Site settings
title: Laura Steele's Blog
email: steele.laura5@gmail.com
description: "Follow Me!"
url: "http://yourdomain.com"
twitter_username: laurasteele5
github_username:  laurasteele5

# Build settings
markdown: kramdown
permalink: pretty
